gnu-octave/statistics

inst/multcompare.m
- the algorithm for the `mvt` CTYPE now performs sampling in chunks of 1000 to avoid memory overload for large numbers of comparisons.
- the total simulation size for "mvt" is not set to 1e+06 and the p-values are truncated at 1e-06
- added automatic support for parallel package (but the parallel package is not a dependence for `multcompare`)
- added `CTYPE` value "dunnett", which uses "mvt"
- updated help info to reflect the above changes
- corrected some formatting errors
=> Various improvements, mainly for "mvt" `CTYPE`

inst/anovan.m
minor changes to allow fitting linear model and ANOVA with just intercept (i.e. no predictors)
=> enabled anovan to run with just intercept (no predictors in `GROUP`)

inst/anovan.m, inst/fitlm.m, inst/multcompare.m
`anovan`:
- added support for missing data in nan (by ommission)
- minor bug fix to prevent warning under some circumstances when creating STATS.coeffnames
- fixed bug that occurred when trying to run model 'interaction' when there is only one factor in GROUP
- changed it so that continuous variables are centered for all contrasts except "treatment"
`fitlm`:
- new function for fitting linear models including demos and BISTs
`multcompare`
- added support for `fitlm`
=> new function `fitlm` and various minor bug fixes in `anovan`

inst/z_test_2.m
See also: https://octave.discourse.group/t/3322
There are multiple tests in that file that use randomly generated input. So, I used a shared block to set a fixed state at the beginning of all of them instead of for each single one.
=> z_test_2.m: Fix the state of the rng for the tests to avoid random fails.

inst/normalise_distribution.m
Needed for passing BISTs on Debian armhf architecture.
See https://buildd.debian.org/status/fetch.php?pkg=octave-statistics&arch=armhf&ver=1.5.2-1&stamp=1671530473&raw=0
=> Increase test tolerance

inst/multcompare.m
- p-values in the table are displayed in APA style in the table (as they are in anovan)
- Added multiple comparison test name to the title of the printed table
- Added 'display', 'off' to some of the tests which did not have it
=> Minor fixes and edits to `multcompare`

inst/fillmissing.m, inst/shadow9/mean.m, inst/shadow9/median.m
* inst/shadow9/mean - Rework function to streamline input processing and reduce called function overhead. Implement reshaping to dim1 for streamlined operations.  Add BISTs to ensure compatible class handling.  
* inst/shadow9/median - Additional called function streamlining.  Simplify code paths when no NaN values are present. Change handling of ints to avoid summation overflow and/or limits of double precision processing for large (u)int64 values.
* inst/fillmissing - Streamline columnwise_median subfunction following improvements to median.
Note: still looking at possibility of fixing bug #54567 (int64 overflow and precision loss) in mean before opening patch to push group to core.
=> mean / median / fillmissing - rework mean, streamline median and fillmissing to fix bug #54567

inst/shadow9/std.m, inst/shadow9/var.m
* input validation for std and var missed some cases where w arrays didn't match the input size. corrected validation logic and added tests.  also corrected variable name typo in docstrings
=> std/var - fix input validation for weight arrays

inst/shadow9/median.m
* scripts/statistics/median.m: Force all vector count and median element indices in the omitnan codepath to be column vectors to avoid sub2ind orientation errors. Add omitnan BISTs including both odd and even column counts with 2D and 3D arrays.
(brings statistics median up to date with changes pushed to octave core default branch)
=> median.m: Correct omitnan internal index orientation (bug #64011)

inst/crossval.m, inst/dist_fun/betapdf.m, inst/regress.m
Needed for reliably passing BISTs on Debian armel, i386 and ppc64el.
=> Increase tests tolerance

inst/crossval.m
Needed for reliably passing BISTs on Debian ppc64el. See https://buildd.debian.org/status/fetch.php?pkg=octave-statistics&arch=ppc64el&ver=1.5.4-3&stamp=1682356882&raw=0
=> Yet another increase of test tolerance

inst/dist_fit/normfit.m
Testing of the normfit function (version 1.6.0 of the statistics package) is failing on my Debian amd64 system, with the error message below. This commit fixes the problem.
```
octave:1> pkg
octave:2> test normfit
***** test
load lightbulb
idx = find (lightbulb(:,2) == 0);
censoring = lightbulb(idx,3) == 1;
[muHat, sigmaHat] = normfit (lightbulb(idx,1), [], censoring);
assert (muHat, 9496.595867378575, 1e-12);
assert (sigmaHat, 3064.021012796456, 1e-12);
!!!!! test failed
ASSERT errors for:  assert (muHat,9496.595867378575,1e-12)
Location  |  Observed  |  Expected  |  Reason
()       9496.5959    9496.5959     Abs err 1.819e-12 exceeds tol 1e-12 by 8e-13
```
=> Increase tolerance of failing BIST for normfit

io.github.gnu_octave.statistics.metainfo.xml
This helps the package show up as an "Addon" to GNU Octave in software stores such as "Gnome Software".
Note that hyphen's are not recommended in the `id`, rather an underscore is used instead.
If you're not familiar with these, here's a thread with a screenshot and explanation:
https://gitlab.com/gnu-octave/octave-pythonic/-/merge_requests/90#note_1480466062
=> Add a metainfo.xml file

inst/ztest2.m
Using Octave 8.3.0, after installing the package statistics 1.6.0 from forge on my machine, attempting to call ztest2 results in the following error:
```
octave:9> [h, pval, z] = ztest2(27, 100, 19, 100)
error: 'stdnormal_cdf' undefined near line 123, column 9
The 'stdnormal_cdf' function belongs to the statistics package from
Octave Forge but has not yet been implemented.
Please read <https://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
error: called from
ztest2 at line 123 column 7
```
Making the change in this pull request and reinstalling from a locally created tarball causes the function to work as expected:
```
octave:13> [h, pval, z] = ztest2(27, 100, 19, 100)
h = 0
pval = 0.1789
z = 1.3442
```
There are likely other functions with similar …
=> update ztest2 for deprecated stdnormal function

inst/chi2gof.m
Newer versions of `makeinfo` seem to be unable to process texinfo when there is text in the same line as the @tex formatter.
Add a newline after @tex to avoid that issue.
Fwiw:
```
$ makeinfo --version
texi2any (GNU texinfo) 7.1
```
```
octave:2> help chi2gof
C:\msys64\tmp\octave-help-xG5EZL:141: fehlplatzierte {
C:\msys64\tmp\octave-help-xG5EZL:141: fehlplatzierte }
C:\msys64\tmp\octave-help-xG5EZL:141: fehlplatzierte {
C:\msys64\tmp\octave-help-xG5EZL:141: fehlplatzierte }
warning: help: Texinfo formatting filter exited abnormally; raw Texinfo source of help text follows...
```
=> chi2gof.m: Add newline after `@tex` to avoid issues with newer makeinfo.

inst/glmfit.m
- The `glmfit` function fits a generalized linear model to the given data using the specified link function and distribution of the response variable. 
- The model is fitted using `IRLS` method. 
- The function take inputs `X -> predictor data`, `y -> response`, `distribution`, `link` and returns a vector `beta` of coefficient estimates for glm. 
- For now, it only supports the `poisson` distribution. 
(https://github.com/gnu-octave/statistics/issues/49) Implementing multinomial regression and generalized linear models functions 
```
X = (1:20)';
beta_true = [1; 0.1];
mu_true = exp(beta_true(1) + beta_true(2) * X);
y = exp(mu_true);
distribution = 'poisson';
link = 'log';
beta = glmfit(X, y, distribution, link);
disp(beta);
```
beta_true is similar to beta
=> Implemented generalized linear model function `glmfit`  

inst/shadow9/mad.m, inst/shadow9/median.m
as per https://savannah.gnu.org/bugs/index.php?65405
codepath with 'omitnan' and vectors in median mishandled all-nan case.  add shortcut codepath for median to handle all-nan's, and add BISTs to median and mad for related cases.
=> median and mad:  correct median all-NaN input handling, add BISTS to median and mad

inst/shadow9/mad.m
*inst/shadow9/mad.m:  Fix condition for replacing output with Inf when using median.  Unlike with mean, instead of condition being when number of Infs is > 0, it should be when it is >numel(x)/2.  The Inf only affects the output when the sorted middle value is Inf.  (also working up fix for similar issue in core so outputs should be compatible.)
=> mad.m:  correct mad handling of vectors with multiple Infs

inst/shadow9/mad.m, inst/shadow9/median.m
* median.m:  add correction for vector of infs that could incorrectly return NaN on codepath with subtraction to avoid overflow. add tests.
=> median: correct handling of even vector with multiple infs

inst/glmfit.m
The BIST for glmfit in not reprodubible:
```
pkg load statistics
while (test ("glmfit", "verbose")) ; endwhile
```
The code above must run forever, but it eventually stops with a failure message like this:
```
!!!!! test failed
ASSERT errors for:  assert (b (2),b_true (2),0.5)
Location  |  Observed  |  Expected  |  Reason
()        0.89439        1.5        Abs err 0.60561 exceeds tol 0.5 by 0.1
```
This is due to the fact that `poissrnd` returns a different value for each call of the BIST. A call to `randp("seed",V)` is necessary for making the BiST reproducible.
=> Make the BIST in glmfit.m reproducible

inst/dist_obj/BinomialDistribution.m
For a thorough discussion on this issue, see:
Nowakowski S (2021) Uniqueness of a median of a binomial distribution with rational probability. Advances in Mathematics: Scientific Journal 10(4):1951-1958. (http://dx.doi.org/10.37418/amsj.10.4.9)
Essentially, when p = 0.5 and N is odd, there would be two "median values" (both integer values around N/2). In this case, the median value should be the fully trimmed mid-range, which happens to be equal to the mean value.
Notice that these changes only cope with the untruncated case. For the general truncated case, the solution seems not to be straightforward. In particular, the code below:
```
pd = BinomialDistribution (5, 0.5);
t = truncate (pd, 0, 5)
t.median ()
```
will produce value `3`, which is wrong (it should be `2.5`).
At any rate, this …
=> Correct median value of binomial distribution when p = 0.5 and N is odd

inst/dist_fun/fpdf.m
The BIST in `inst/dist_fun/fpdf.m` fails randomly:
```
octave:1> pkg load statistics
octave:2> while 1 ; if ! test("fpdf", "verbose") ; break ; endif ; endwhile
[…]
!!!!! test failed
ASSERT errors for:  assert (fpdf (xr, 1, 2),yr,5 * eps)
Location  |  Observed  |  Expected  |  Reason
()         4.4017       4.4017      Abs err 2.6645e-15 exceeds tol 1.1102e-15 by 2e-15
shared variables 
x =
-1.0000        0   0.5000   1.0000   2.0000
y =
0        0   0.4444   0.2500   0.1111
```
This proposed commit fixes the problem, by using `rand("seed")`.
=> Make BIST in fpdf.m reproducible

NEWS, inst/fillmissing.m
* fillmissing: ensure movmedian doesn't ignore 'missinglocation' option.  Large number of whitespaces and coding style adjustments for consistency (no functional changes there)
* update News
=> fillmissing: correct bug with 'movmedian' and 'missinglocations', code style and whitespace improvements

inst/dist_obj/private/__plot__.m
just takes the real length of `xx` instead of the returned, and possibly wrong length from `cdfcalc`
=> [#162] fix index error in PoissonDistribution.plot()

inst/dist_fun/chi2cdf.m
Currently the Chi-square cumulative distribution function produces the same output regardless of the value of the "upper" argument: 
```
> pkg load statistics
> chi2cdf(50,50)
ans = 0.5266
> chi2cdf(50,50, "upper")
ans = 0.5266
```
This seems to be due to an issue in the initial 'Check for valid "upper" flag' that always makes the `uflag` empty. 
The proposed fix solves this issue:
```
> chi2cdf(50,50)
ans = 0.5266
> chi2cdf(50,50, "upper")
ans = 0.4734
> chi2cdf2(50,50, "wrong_arg")
error: chi2cdf: invalid argument for upper tail.
error: called from
chi2cdf2 at line 11 column 7
```
Thanks for providing the community with this great package!
=> Bug fix in "upper" argument for the cdf of the Chi-square distribution

inst/dist_wrap/fitdist.m
This PR removes the warnings that appear with octave 11.0.0 & makeinfo 7.1,
while installing statistics.
Opened as discussed with @pr0m1th3as
=> Fix warnings during installation of statistics

inst/Classification/private/parseScoreTransform.m
Replaces incorrect use of 'exp .^' with proper 'exp' function calls in anonymous functions for 'doublelogit', 'logit', and 'symmetriclogit' score transforms. Shouldn't the syntax of `exp()` be like this, or is `exp` a custom variable?
=> Fix `exp()` usage in parseScoreTransform.m

inst/@cvpartition/cvpartition.m
The Leave-One-Out method requires that each test set contains only one sample, while the training set consists of the remaining n−1 samples.
=> cvpartition: fix `leaveout`method and corresponding test case
